// Export all services from a single entry point
export { authService } from './auth';
export { departmentService } from './departments';
export { projectService } from './projects';
export { reportService } from './reports';
export { announcementService } from './announcements';
export { eventService } from './events';
export { documentService } from './documents';
export { messageService } from './messages';
export { settingsService, languageService } from './settings';
export { uploadService } from './upload';
export { heroSliderService } from './heroSliders';
export { cityStatsService } from './cityStats';
export { servicesService } from './services';
export { languagesService } from './languages';
export { subscribersService } from './subscribers';
export { newsletterService } from './newsletter';
export { newsService } from './news';
export { newsCategoriesService } from './newsCategories';
export { newsTagsService } from './newsTags';
export { leaderService } from './leaders';
export { uiTranslationsService } from './uiTranslations';
export { pageHeroSlidesService } from './pageHeroSlides';
export { departmentTranslationsService } from './departmentTranslations';
export { serviceTranslationsService } from './serviceTranslations';
export { newsTranslationsService } from './newsTranslations';
export { newsCategoryTranslationsService } from './newsCategoryTranslations';
export { newsTagTranslationsService } from './newsTagTranslations';
export { newsCategoryMapService } from './newsCategoryMap';
export { newsTagMapService } from './newsTagMap';
export { mediaService } from './media';
export { analyticsService } from './analytics';
export { default as api, API_URL } from './api';
